- name: "Clone the machine-setup playbook to the target user directory"
  ansible.builtin.include_tasks: clone_pb.yml

- name: "Move vault password file to target user dir, optionally symlinking"
  ansible.builtin.include_tasks: mv_vault_pswd.yml

