- name: >-
    Move '{{ cfg_user_playbook_source_vault_passwd_path }}' to
    '{{ cfg_user_playbook_target_vault_passwd_symlink_to_path }}'
  ansible.builtin.command:
    cmd: >-
      mv
      {{ cfg_user_playbook_source_vault_passwd_path | quote }}
      {{ cfg_user_playbook_target_vault_passwd_symlink_to_path | quote }}
    removes: "{{ cfg_user_playbook_source_vault_passwd_path }}"
  become: true
  become_user: root

- name: "Set owner and permissions on '{{ cfg_user_playbook_target_vault_passwd_symlink_to_path }}'"
  ansible.builtin.file:
    path: "{{ cfg_user_playbook_target_vault_passwd_symlink_to_path }}"
    owner: "{{ cfg_user_playbook_target_user_name }}"
    group: "{{ cfg_user_playbook_target_group_name }}"
    mode: '644'
  become: true
  become_user: root

- name: >-
    Symlink '{{ cfg_user_playbook_target_vault_passwd_symlink_from_path }}'
    to '{{ cfg_user_playbook_target_vault_passwd_symlink_to_path }}'
  ansible.builtin.file:
    src: "{{ cfg_user_playbook_target_vault_passwd_symlink_to_path }}"
    dest: "{{ cfg_user_playbook_target_vault_passwd_symlink_from_path }}"
    owner: "{{ cfg_user_playbook_target_user_name }}"
    state: link
    force: true
  become: true
  become_user: root
  when: cfg_user_playbook_target_vault_passwd_symlink_from_path !=
        cfg_user_playbook_target_vault_passwd_symlink_to_path

- name: "Set owner and permissions on '{{ cfg_user_playbook_target_vault_passwd_symlink_from_path }}'"
  ansible.builtin.file:
    path: "{{ cfg_user_playbook_target_vault_passwd_symlink_from_path }}"
    owner: "{{ cfg_user_playbook_target_user_name }}"
    group: "{{ cfg_user_playbook_target_group_name }}"
    mode: '755'
  become: true
  become_user: root
  when: cfg_user_playbook_target_vault_passwd_symlink_from_path !=
        cfg_user_playbook_target_vault_passwd_symlink_to_path

